//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.BusinessLogic.WCF.UsersWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsersWcfService.IUsersWcfService")]
    public interface IUsersWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersWcfService/GetUserByLogin", ReplyAction="http://tempuri.org/IUsersWcfService/GetUserByLoginResponse")]
        BookStore.Model.User GetUserByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersWcfService/GetUserByLogin", ReplyAction="http://tempuri.org/IUsersWcfService/GetUserByLoginResponse")]
        System.Threading.Tasks.Task<BookStore.Model.User> GetUserByLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersWcfService/GetEmployeeByUserId", ReplyAction="http://tempuri.org/IUsersWcfService/GetEmployeeByUserIdResponse")]
        BookStore.Model.Employee GetEmployeeByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersWcfService/GetEmployeeByUserId", ReplyAction="http://tempuri.org/IUsersWcfService/GetEmployeeByUserIdResponse")]
        System.Threading.Tasks.Task<BookStore.Model.Employee> GetEmployeeByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersWcfService/GetAllCustomers", ReplyAction="http://tempuri.org/IUsersWcfService/GetAllCustomersResponse")]
        System.Collections.Generic.List<BookStore.Model.Customer> GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersWcfService/GetAllCustomers", ReplyAction="http://tempuri.org/IUsersWcfService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookStore.Model.Customer>> GetAllCustomersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersWcfServiceChannel : BookStore.BusinessLogic.WCF.UsersWcfService.IUsersWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersWcfServiceClient : System.ServiceModel.ClientBase<BookStore.BusinessLogic.WCF.UsersWcfService.IUsersWcfService>, BookStore.BusinessLogic.WCF.UsersWcfService.IUsersWcfService {
        
        public UsersWcfServiceClient() {
        }
        
        public UsersWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookStore.Model.User GetUserByLogin(string login) {
            return base.Channel.GetUserByLogin(login);
        }
        
        public System.Threading.Tasks.Task<BookStore.Model.User> GetUserByLoginAsync(string login) {
            return base.Channel.GetUserByLoginAsync(login);
        }
        
        public BookStore.Model.Employee GetEmployeeByUserId(int userId) {
            return base.Channel.GetEmployeeByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<BookStore.Model.Employee> GetEmployeeByUserIdAsync(int userId) {
            return base.Channel.GetEmployeeByUserIdAsync(userId);
        }
        
        public System.Collections.Generic.List<BookStore.Model.Customer> GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookStore.Model.Customer>> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
    }
}
