//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.BusinessLogic.WCF.BooksWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BooksWcfService.IBooksWcfService")]
    public interface IBooksWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBooksWcfService/SearchBooks", ReplyAction="http://tempuri.org/IBooksWcfService/SearchBooksResponse")]
        System.Collections.Generic.List<BookStore.Model.BookAmount> SearchBooks(int branchId, string isbn, string searchString, bool onHandOnly);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBooksWcfService/SearchBooks", ReplyAction="http://tempuri.org/IBooksWcfService/SearchBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookStore.Model.BookAmount>> SearchBooksAsync(int branchId, string isbn, string searchString, bool onHandOnly);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBooksWcfServiceChannel : BookStore.BusinessLogic.WCF.BooksWcfService.IBooksWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BooksWcfServiceClient : System.ServiceModel.ClientBase<BookStore.BusinessLogic.WCF.BooksWcfService.IBooksWcfService>, BookStore.BusinessLogic.WCF.BooksWcfService.IBooksWcfService {
        
        public BooksWcfServiceClient() {
        }
        
        public BooksWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BooksWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BookStore.Model.BookAmount> SearchBooks(int branchId, string isbn, string searchString, bool onHandOnly) {
            return base.Channel.SearchBooks(branchId, isbn, searchString, onHandOnly);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookStore.Model.BookAmount>> SearchBooksAsync(int branchId, string isbn, string searchString, bool onHandOnly) {
            return base.Channel.SearchBooksAsync(branchId, isbn, searchString, onHandOnly);
        }
    }
}
